### ISSUE TITLE
  object 'NJ' of mode 'function' was not found

### ISSUE THREAD

**Issue by dempc01** [mennodejong1986/SambaR#10]
I am having an issue with findstructure:

**Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'NJ' of mode 'function' was not found
In addition: Warning messages:
1: In bplt(at[i], wid = width[i], stats = z$stats[, i], out = z$out[z$group ==  :
  Outlier (-Inf) in boxplot 2 is not drawn
2: In bplt(at[i], wid = width[i], stats = z$stats[, i], out = z$out[z$group ==  :
  Outlier (-Inf) in boxplot 2 is not drawn
3: In bplt(at[i], wid = width[i], stats = z$stats[, i], out = z$out[z$group ==  :**

When I set do_tree to FALSE then I get an error with nei:

**Error in if (any(df < 0)) stop("negative entries in table") : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In bplt(at[i], wid = width[i], stats = z$stats[, i], out = z$out[z$group ==  :
  Outlier (-Inf) in boxplot 2 is not drawn
2: In bplt(at[i], wid = width[i], stats = z$stats[, i], out = z$out[z$group ==  :
  Outlier (-Inf) in boxplot 2 is not drawn
3: In bplt(at[i], wid = width[i], stats = z$stats[, i], out = z$out[z$group ==  :**

I have run SambaR many times for almost the exact same dataset but this started following updating R and some of the packages. Any help would be appreciated.

**Comment by mennodejong1986** [comment]
Could you check what you get when you type 'NJ'? It should tell that NJ is a function. If not, and if it is not an important object, you could simply remove it - i.e, rm(NJ) - and then try running the findstructure function again. 

Considering the second error, when exactly does this error occur? Sometimes the only solution is to set the flag 'do_nei' to FALSE.

**Comment by dempc01** [comment]
No object 'NJ' is found. The second error occurs right after starting nei but only happens if do_tree = FALSE, otherwise nei works before encountering the NJ error.

**Comment by mennodejong1986** [comment]
Apologies for my late reply. So far I have not been able to reproduce your error. 

Concerning the error regarding the tree building ('NJ of mode function not found'), could you check whether the package 'poppr' is installed and loaded:
"poppr" %in% rownames(installed.packages())
"poppr" %in% (.packages())

If poppr is indeed installed and loaded, could you next check if you can reproduce the error running the following commands:
popprtree(do_analysis=TRUE,mymethod="NJ",mydistance="bitwise.dist")
popprtree(do_analysis=TRUE,mymethod="upgma",mydistance="bitwise.dist")

Regarding the error about negative entries, you can potentially try to circumvent this by setting the flag do_pi to FALSE as well. However, this is not an elegant solution, as it simply skips the analyses.
I wonder whether the problem is caused due to low number of snps and or inds. Ideally, you would have at least 500 or more SNPs. You could check using the commands:
table(snps$filter)
table(inds$filter)

Could you perhaps provide more information about your data (number of snps, individuals, type of data, etc)?

I will upload now a newer version of SambaR in which another issue with the findstructure function (regarding BAPT test) is solved.

**Comment by dempc01** [comment]
Updating to the latest version of R and updating all packages (along with using the latest SambaR) seems to have helped solve the issue. I am sticking with using "do_tree = FALSE" since I do not need it which may be bypassing the error as well.

**Comment by mennodejong1986** [comment]
Great! Still not sure what exactly caused the error, but at least it is working.
