### ISSUE TITLE
LEAstructure error

### ISSUE THREAD

**Issue by Lomousmishra** [mennodejong1986/SambaR#14]
Hi, Mennodejong
I am repeatedly getting the following error while running findstructure command;
Error in LEAstructureplot(mindemes = Kmin, maxdemes = Kmax, export = "eps",  : 
  argument 5 matches multiple formal arguments
Can you suggest how to overcome this.
Also while loading SNP data for Selection with more than 400,000 snps,  process is getting killed (with 10 GB RAM and 4 cpu core).
Thanks in advance.

**Comment by mennodejong1986** [comment]
Hi Lomous,

If I am not mistaken, this error is now solved with the current version on Github. Simply download and source the current SambaR script and try rerunning the findstructure() function again (no need to reload the data). Let me know if the problem persists.

Concerning the other problem, 400K snps is indeed on the high side. Do you mean this problem occur when running the selectionanalyses() function? Can you see which test exactly (GWDS, PCadapt, OutFLANK) is causing the problem? You could try skipping this particular test (e.g., do_pcadapt=FALSE in case the problem is caused by pcadapt, or do_outflank=FALSE if the problem is caused by Outflank). The only other two options are to run the analyses on a more powerful computer or to downsample the dataset (e.g., thin the data or filter on LD before importing in R).

Hope this helps!

**Comment by Lomousmishra** [comment]
Hi Mennodejong,
I am using the SAMBAR_v1.05, which is current version and fusing ollowing command;
findstructure(Kmax=4, add_legend=TRUE, short_pop=NULL, pop_order=NULL) and findstructure(onlyLEA=TRUE, Kmax=4, add_legend=TRUE),
But in both cases got same error as above.
And with thinned data Selection runs are fine, i just wanted to include more markers but failed in import data stage.
Thanks

**Comment by mennodejong1986** [comment]
Hi, in case of minor changes, I do not edit the version number. So unless you downloaded the source script within the last few days, it is likely that the current version on Github is slightly different then the one you downloaded. If I remember correctly, I solved this issue with LEA only a few days ago. Therefore, if you download the current version it might run LEA without errors (but correct me if I am wrong).

**Comment by Lomousmishra** [comment]
Hi, problem resolved after downloading recent version.
Thank you very much.
