### ISSUE TITLE
Possible new option?

### ISSUE THREAD

**Issue by bmillerlab** [mennodejong1986/SambaR#27]
Hello, I have been using SambaR the last year and have found it very useful. So first, thanks for this software.  

What I have been wondering is if it would be hard to make it possible to change the filtered data produced by SambaR back into a genlight object, so essentially a sambar2genlight option?  The reason I am wondering is because I've tried to use other software to reproduce the subset of snps I have after running the filterdata() function in SambaR and I can't replicate the subset.  I have tried to use the exportsambarfiles() option, but I can't get the output back into a genlight or genind format correctly - which is what I actually want.

Thank you again.

**Comment by mennodejong1986** [comment]
Glad to hear that SambaR has been of use to you. Are the following commands what you are looking for?

mymat<-as.matrix(mygenlight[inds$filter,snps$filter])
mygl<-as.genlight(mymat)
inddf<-inds[inds$filter,c("name","pop")]
snpdf<-snps[snps$filter,c("name","chr","pos")]


#If wanted, you can also proceed and generate new sambar objects.
#First change working (otherwise files will be overwritten), and then run:
genlight2sambar(genlight_object="mygl",do_confirm=FALSE,popvector=as.character(inddf$pop),pop_order=NULL,colourvector=NULL) 
# to keep all snps, disable all filters:    
filterdata(indmiss=1,snpmiss=1,min_mac=1,dohefilter=FALSE,snpdepthfilter=FALSE,min_spacing=1)

#After the filterdata function completed, you can optionally create a genind object:
genlight2genind(input=mygenlight)

**Comment by bmillerlab** [comment]
Thank you.  I am going to try these out, and I think this is just what I wanted to be able to do.  I appreciate your help!
