### ISSUE TITLE
PCAdapt do_pcadapt = FALSE not working in getpackages

### ISSUE THREAD

**Issue by MaevaTecher** [mennodejong1986/SambaR#7]
Dear Menno de Jong,

First of all thanks for this amazing package and for a really great tutorial with human-like messages in the console!

I am having some issues with the error related to PCAdapt library and just noticed that a new version 4.3.0 is available since last month. I tried to modify the code for getpackages to overide this problem, as I was able to install it by myself. I must do it wrong as the getpackages function keep erasing my newest version... do you think it would be possible to update this?

Thanks in advance!

Maeva

**Comment by mennodejong1986** [comment]
Hi Maeva, thanks for the positive feedback! Yes, for some reason the getpackages function behaves problematic for PCadapt and other bioconductor packages. Before I look into this, could you confirm that you 'told' SambaR not to attempt to install 'PCadapt', by setting within the mypackageslist.txt file the flags 'do_install' and 'do_load' to FALSE?
 
Also, and importantly, SambaR needs the old PCadapt version 4.1.0. The reason is that a crucial utility of PCadapt has been deprecated in later versions, and as a result the selectionanalyses() function will not run properly if using a more recent PCadapt version. Are you sure you want to install the latest PCadapt version?

**Comment by MaevaTecher** [comment]
Hi Menno,

Thanks for your prompt reply and I understand now the interest of keeping the previous version of 'pcadapt'. Actually, after following your suggestion with mypackageslist.txt, I had no issues with this error.

However I figured out that the main issue was not with your code but with my version of gfortran which kept popping up when I tried to install the old version 4.1.0 of pcadapt. So in case, someone else has the same issue as me, I just follow this https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/ and it solved it

Thanks again for the help!
